version: '3'
networks:
    micro-orm.net:
      driver: bridge
services:
  micro-orm.php:
    image: 'canals/php:latest'
    ports:
      - '2080:80'
    volumes:
      - ../:/var/www
    working_dir: /var/www/
    networks:
      - micro-orm.net
    depends_on:
      - micro-orm.db

  micro-orm.db:
    image: 'postgres:latest'
    command: '--collation-server=utf8_general_ci'
    env_file: .env
    ports:
      - '5432:5432'
    networks:
      - micro-orm.net

  micro-orm.adminer:
    image: adminer
    ports:
      - '8082:8080'
    networks:
      - micro-orm.net