version: '1'
networks:
    micro-orm.net:
      driver: bridge
services:
  micro-orm.php:
    image: 'canals/php:latest'
    ports:
      - '2080:80'
    volumes:
      - ../:/var/www
    working_dir: /var/www/
    networks:
      - micro-orm.net
    depends_on:
      - micro-orm.db

  micro-orm.db:
    image: 'postgres:latest'
    env_file: ./src/config/.env
    ports:
      - '5432:5432'
    networks:
      - micro-orm.net

  micro-orm.adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '8082:8080'
    networks:
      - micro-orm.net